title:             franklinqin0
email:             franklinqin0@gmail.com
description:       Franklin Qin's Tech Blog
author:            Franklin Qin
baseurl:           ""
url:               "http://franklinqin0.github.io"

# Social Profiles
# twitter_username:  SBootstrap
github_username:   franklinqin0
facebook_username: franklinqin0

# Build settings
markdown:          kramdown
paginate:          8
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# theme:             jekyll-theme-clean-blog