name: Deploy GitHub Pages

# once pushed to master branch
on:
  push:
    branches:
      - master

# jobs to build and deploy
jobs:
  build-and-deploy:
    # server env: latest Ubuntu
    runs-on: ubuntu-latest
    steps:
      # pull project
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # build project
      - name: Build
        run: npm install && npm run build

      # deploy to Github Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.everything }}
          branch: gh-pages
          folder: docs/.vuepress/dist
